# This is a basic workflow to help you get started with Actions

name: Build documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "documentation"
  documentation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            ~/.cache/pip3
            /usr/bin/pandoc
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-dependencies

      # Runs a single command using the runners shell
      - name: Install dependecies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          pip3 install scrap_engine pdoc3
          sudo apt-get install pandoc

      # Build documentation
      - name: Build documentation
        run: |
          pdoc --html pokete_classes
          pdoc --html pokete_data
          pdoc --html pokete.py
          pdoc --html gen-wiki.py
          pdoc --html pokete_general_use_fns.py
      - name: Preprocess page files
        run: |
          python3 ./prepare_pages.py before
          cp ./prepare_pages.py /tmp/prepare_pages.py
      - name: Move files to /tmp
        run: |
          mv 'html/' 'assets/' /tmp
          mv 'wiki.md' /tmp/wiki.md
          mv 'HowToPlay.md' /tmp/HowToPlay.md
          mv 'Changelog.md' /tmp/Changelog.md
          mv 'README.md' /tmp/README.md
          sed -i "s/wiki\.md/.\/wiki.html/g" /tmp/README.md
          sed -i "s/Changelog\.md/.\/Changelog.html/g" /tmp/README.md
          sed -i "s/HowToPlay\.md/.\/HowToPlay.html/g" /tmp/README.md
      - name: Switch branch to gh-pages
        uses: actions/checkout/@v2
        with:
          ref: 'gh-pages'
      - name: Generate gh-pages page
        run: |
          rm -rf ./doc ./assets
          mv '/tmp/html/' ./doc
          mv '/tmp/assets/' .
          pandoc /tmp/wiki.md -o 'wiki.html'
          python3 /tmp/prepare_pages.py after
          #pandoc /tmp/HowToPlay.md -o 'HowToPlay.html' --standalone
          #pandoc /tmp/Changelog.md -o 'Changelog.html' --standalone
          mv /tmp/README.md ./index.md
          mv /tmp/HowToPlay.md ./HowToPlay.md
          mv /tmp/Changelog.md ./Changelog.md
      # Push to github_pages
      - name: Release documentation
        run: |
          git config --local user.name  ${{ github.actor }}
          if [[ $(git diff) != "" ]]
          then
          git add .
            git commit -m "Updated pages"
          fi
    
      - name: Push changes  # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: false
