# This is a basic workflow to help you get started with Actions

name: gen-wiki


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  gen-wiki:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: install deps
        run: pip3 install scrap_engine

      - name: gen-wiki
        run: python3 ./gen-wiki.py
        
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh }}
    
      - name: check for changes
        run: git status
    
      - name: stage changed files
        run: git add .
    
      - name: commit changed files
        run: git commit -m "Updated wiki"
    
      - name: fetch from master
        run: git fetch origin master
      
      - name: push code to master
        run: git push origin HEAD:master

