# This is a basic workflow to help you get started with Actions

name: gen-wiki


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  gen-wiki:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: install deps
        run: pip3 install scrap_engine

      - name: gen-wiki
        run: python3 ./gen-wiki.py
